version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nikita
      POSTGRES_USER: nikitauser
      POSTGRES_PASSWORD: nikitapass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nikitauser -d nikita -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      bash -c "./wait-for-postgres.sh db:5432 -- 
               python manage.py migrate &&
               gunicorn --bind 0.0.0.0:8000 Nikita.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
