# Generated by Django 5.0.6 on 2024-05-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('event_type', models.CharField(choices=[('admin', 'Административное'), ('sso', 'ССО')], max_length=255, verbose_name='Тип события')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображения')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory', verbose_name='Общежитие')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('institute', models.CharField(blank=True, max_length=255, null=True, verbose_name='Институт')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Группа')),
                ('room', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комната')),
                ('admin_points', models.IntegerField(blank=True, default=0, null=True, verbose_name='Административные баллы')),
                ('sso_points', models.IntegerField(blank=True, default=0, null=True, verbose_name='ССО баллы')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory', verbose_name='Общежитие')),
            ],
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.event', verbose_name='Событие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.student', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.student', verbose_name='Студент'),
        ),
    ]
