# Generated by Django 5.0.6 on 2024-05-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_remove_event_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointshistory', to='dormitory.student', verbose_name='Студент'),
        ),
    ]
