# Generated by Django 5.0.6 on 2024-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_dormitory_address_alter_dormitory_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
