# Generated by Django 5.0.6 on 2024-05-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_alter_pointshistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dormitory',
            options={'verbose_name': 'Общежитие', 'verbose_name_plural': 'Общежития'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='pointshistory',
            options={'verbose_name': 'История баллов', 'verbose_name_plural': 'История баллов'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
